import {
  About,
  AboutLogo,
  AboutUstav,
  AdEmployees,
  AdProfDevelop,
  Advanced,
  Aplicant,
  Budget,
  Contacts,
  Cooperation,
  Council,
  EduAnket,
  EduAspirantura,
  EduBakalavr,
  Education,
  EduDoktorantura,
  EduKafedBP,
  EduKafedEM,
  EduKafedGMU,
  EduMagistratura,
  EduSPO,
  History,
  Integrity,
  Journal,
  LawsGeneral,
  LawsInternal,
  Main,
  News,
  Professors,
  QualitySystem,
  Schedule,
  Structure,
  Union,
} from "@/components/pages";

const routes = [
  { path: "/", element: <Main /> },
  { path: "/about", element: <About /> },
  { path: "/about/charter", element: <AboutUstav /> },
  { path: "/about/logotip", element: <AboutLogo /> },
  { path: "/about/history", element: <History /> },
  { path: "/about/structure", element: <Structure /> },
  { path: "/about/council", element: <Council /> },
  { path: "/about/union", element: <Union /> },
  { path: "/about/quality-system", element: <QualitySystem /> },
  { path: "/about/journal", element: <Journal /> },
  { path: "/about/budget", element: <Budget /> },
  { path: "/about/professors", element: <Professors /> },
  { path: "/about/cooperation", element: <Cooperation /> },
  { path: "/about/integrity", element: <Integrity /> },
  { path: "/about/laws-general", element: <LawsGeneral /> },
  { path: "/about/laws-internal", element: <LawsInternal /> },
  { path: "/education", element: <Education /> },
  { path: "/education/spo", element: <EduSPO /> },
  { path: "/education/bakalavr", element: <EduBakalavr /> },
  { path: "/education/magistr", element: <EduMagistratura /> },
  { path: "/education/doctor", element: <EduDoktorantura /> },
  { path: "/education/aspirant", element: <EduAspirantura /> },
  { path: "/education/kafedgmu", element: <EduKafedGMU /> },
  { path: "/education/kafedem", element: <EduKafedEM /> },
  { path: "/education/kafedbp", element: <EduKafedBP /> },
  { path: "/education/anket", element: <EduAnket /> },
  { path: "/schedule", element: <Schedule /> },
  { path: "/contacts", element: <Contacts /> },
  { path: "/advanced", element: <Advanced /> },
  { path: "/advanced/profdevelop", element: <AdProfDevelop /> },
  { path: "/advanced/employees", element: <AdEmployees /> },
  { path: "/aplicant2025", element: <Aplicant /> },
  { path: "/news", element: <News /> },
];

export default routes;
